<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net6.0-windows;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>True</EnableWindowsTargeting>
    <ApplicationIcon>Resources\Penguin.ico</ApplicationIcon>
    <LangVersion>latest</LangVersion>
    <Version>1.0.1.6</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="appsettings.yml" CopyToOutputDirectory="Always" />
    <Content Include="appsettings.json" CopyToOutputDirectory="Always" />
    <Content Include="Resources\Penguin.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IceTea.SocketStandard" Version="2.1.0" />
    <ProjectReference Include="..\CustomControlsDemoModule\CustomControlsDemoModule.csproj" />
    <ProjectReference Include="..\MusicPlayerModule\MusicPlayerModule.csproj" />
    <ProjectReference Include="..\SqlCreatorModule\SqlCreatorModule.csproj" />
    <Resource Include="Resources\apple.ico" />
    <Resource Include="Resources\网络.png" />
    <Resource Include="Resources\雪山祥云.png" />
  </ItemGroup>
</Project>
