<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>True</EnableWindowsTargeting>
    <ApplicationIcon>Resources\Penguin.ico</ApplicationIcon>
    <LangVersion>latest</LangVersion>
    <Version>1.0.1.6</Version>
    <Configurations>Debug;Release;ClickOnce</Configurations>
  </PropertyGroup>
  
  <Choose>
    <!-- 当使用 ClickOnce 配置时，仅编译 net8.0-windows -->
    <When Condition="'$(Configuration)' == 'ClickOnce'">
      <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
      </PropertyGroup>
    </When>
    <!-- 其他情况（Debug、Release 以及自定义配置），编译多版本 -->
    <Otherwise>
      <PropertyGroup>
        <TargetFrameworks>net462;net6.0-windows;net8.0-windows</TargetFrameworks>
      </PropertyGroup>
    </Otherwise>
  </Choose>

  <ItemGroup>
    <Content Include="appsettings.yml" CopyToOutputDirectory="Always" />
    <Content Include="appsettings.json" CopyToOutputDirectory="Always" />
    <Content Include="Resources\Penguin.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IceTea.SocketStandard" Version="2.1.2" />
    <ProjectReference Include="..\CustomControlsDemoModule\CustomControlsDemoModule.csproj" />
    <ProjectReference Include="..\MusicPlayerModule\MusicPlayerModule.csproj" />
    <ProjectReference Include="..\SqlCreatorModule\SqlCreatorModule.csproj" />
    <Resource Include="Resources\apple.ico" />
    <Resource Include="Resources\网络.png" />
    <Resource Include="Resources\雪山祥云.png" />
  </ItemGroup>
</Project>
