<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net462;net6.0-windows;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <EnableWindowsTargeting>True</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="ExportModels\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IceTea.SqlStandard" Version="1.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PrismAppBasicLib\PrismAppBasicLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="DBConfig.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
