version: '1.0'
name: pipeline-20241102
displayName: pipeline-20241102
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
  pr:
    branches:
      prefix:
        - ''
stages:
  - name: stage-8d7a5e88
    displayName: 扫描
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: sc@opensca
        name: open_sca
        displayName: OpenSCA 开源组件检测
        detectPath: ./
        notify: []
        strategy:
          retry: '0'
  - name: stage-122a46db
    displayName: 推送并触发
    strategy: naturally
    trigger: auto
    executor:
      - six-six-god
    steps:
      - step: build@dotnet
        name: build_dotnet
        displayName: .NET Core 构建
        dotnetVersion: '6.0'
        commands:
          - '# input your command here'
          - dotnet restore
          - dotnet publish -c Release -o out
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./out
        caches:
          - ~/.nuget/packages
        notify: []
        strategy:
          retry: '1'
          expression: []
  - name: stage-6b91d06d
    displayName: 发布
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
  - name: stage-c014876b
    displayName: 部署
    strategy: naturally
    trigger: auto
    executor:
      - six-six-god
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: Host
          hostID:
            - df90e9e4-3334-42b3-848f-0875ca11cf80
        deployArtifact:
          - source: build
            name: output
            target: ~/gitee_go/deploy
            dependArtifact: output
        script:
          - '# 功能：部署脚本会在部署主机组的每台机器上执行'
          - '# 使用场景：先将制品包解压缩到指定目录中，再执行启动脚本deploy.sh，脚本示例地址：https://gitee.com/gitee-go/spring-boot-maven-deploy-case/blob/master/deploy.sh'
          - '# mkdir -p /home/admin/app'
          - '# tar zxvf ~/gitee_go/deploy/output.tar.gz -C /home/admin/app'
          - '# sh /home/admin/app/deploy.sh restart'
          - '# 如果你是php之类的无需制品包的制品方式，可以使用 git clone 或者 git pull 将源代码更新到服务器，再执行其他命令'
          - '# git clone ***@***.git'
          - echo 'Hello Gitee Go!'
        notify: []
        strategy:
          retry: '0'
